### ISSUE TITLE
Calibrate USRP Delay Needs Arguments Fix for USRP Detection

### ISSUE THREAD

**Issue by jholtom** [ShaneFlandermeyer/gr-plasma#1]
/home/jholtom/projects/gr-plasma/apps/calibrate_usrp_delay.cc:142:40: error: cannot convert ‘const char [1]’ to ‘const uhd::device_addr_t&’
  142 |     usrp = uhd::usrp::multi_usrp::make("");
      |                                        ^~
      |                                        |
      |                                        const char [1]
In file included from /home/jholtom/projects/gr-plasma/apps/calibrate_usrp_delay.cc:3:
/usr/include/uhd/usrp/multi_usrp.hpp:120:43: note:   initializing argument 1 of ‘static uhd::usrp::multi_usrp::sptr uhd::usrp::multi_usrp::make(const uhd::device_addr_t&)’
  120 |     static sptr make(const device_addr_t& dev_addr);

**Comment by ShaneFlandermeyer** [comment]
Fixed in https://github.com/ShaneFlandermeyer/gr-plasma/commit/f9bce87a4da446ff2f32a531c5a4455a8dd81a4e
