### ISSUE TITLE
Usrp Radar: calibration file

### ISSUE THREAD

**Issue by luxiaohongzb** [ShaneFlandermeyer/gr-plasma#13]
Hi, I am new in this field. I wonder what the calibration file is used for and where can I find this file or generate this file?  You help means a lot to me.

**Comment by ShaneFlandermeyer** [comment]
USRP radios have a delay between the start of transmit and receive that depends on the radio model, master clock rate, and sample rate. The calibration file is just a json file that stores how many samples of delay there are for each configuration.

You can measure this delay by transmitting a simple square wave in loopback, saving the data, then looking at how many samples it takes for the waveform to actually be received. You could also do matched filtering to extract the peak automatically. 

As an example, this is what my json config file looks like for the USRP B210: 

```[json]
{
 "B210": [
  {
   "delay": 46,
   "master_clock_rate": 40000000.0,
   "samp_rate": 10000000.0
  },
  {
   "delay": 165,
   "master_clock_rate": 20000000.0,
   "samp_rate": 20000000.0
  },
  {
   "delay": 165,
   "master_clock_rate": 30000000.0,
   "samp_rate": 30000000.0
  },
  {
   "delay": 165,
   "master_clock_rate": 40000000.0,
   "samp_rate": 40000000.0
  },
  {
   "delay": 158,
   "master_clock_rate": 50000000.0,
   "samp_rate": 50000000.0
  }
 ]
}
```

**Comment by luxiaohongzb** [comment]
Thanks a lot for your reply.
