### ISSUE TITLE
some questions about the waveform_controller block?

### ISSUE THREAD

**Issue by Fangrf** [ShaneFlandermeyer/gr-plasma#14]
In the main branch, from the code, the waveform_controller block seems to only update the prf and add it to the pdu. It doesn't update the data. But in the waveform_controller.h ,  " block by zero-padding the input waveform to match the number of samples in a
  pulse repetition interval (PRI)" , this does not seem to have been achieved.

**Comment by ShaneFlandermeyer** [comment]
The latest version of this repo uses the "CW to pulsed" block to achieve this functionality. Thanks for raising this issue, I will fix the screenshot in the README to reflect this.
