### ISSUE TITLE
cw to plus

### ISSUE THREAD

**Issue by aimiruisi** [ShaneFlandermeyer/gr-plasma#15]
Hi, I am trying to make a radar that needs to make a Pulse frequency modulation radar and I want to use the block UHD: USRP Radar, how can I make that? Or how can I make module "cw to pluse" to be used?

**Comment by ShaneFlandermeyer** [comment]
The "CW To Pulsed" block should fit your use case. You can dynamically change the pulse repetition frequency in the CW->Pulsed block by specifying the desired PRF in the metadata of the waveform PDU message. By default, the block uses ```radar:prf``` as the dict key.

**Comment by ShaneFlandermeyer** [comment]
I also just pushed a commit to the develop branch which allows you to specify the PRF metadata and waveform samples in separate messages. Hopefully this is useful for your application.
