### ISSUE TITLE
Something missing 

### ISSUE THREAD

**Issue by Raidfire-SDR** [ShaneFlandermeyer/gr-plasma#2]
Hi I'm getting a make error whatever bundle of source code I use,
Env is Ubuntu 22.04, gnuradio 3.10 installed with pybombs, arrayfire built from source, dsp plasma built from source, Using a force build i can confirm this is the only block that wont build, I have a feeling the error stems from the dsp install that couldn't find the gnuradio runtime so i used cmake -DCMAKE_INSTALL_PREFIX=/home/raidfire/prefix-gr310radar/ .. as the dsp  build command, this then completes and installs sucessfully, but i think it is causing issues down the line with the gr block. error is on 'make' after cmake completes without issue.

Any idea what I'm missing?

[  3%] Building CXX object lib/CMakeFiles/gnuradio-plasma.dir/lfm_source_impl.cc.o
/home/raidfire/gr-plasma-1.1.0-rc1/lib/lfm_source_impl.cc: In constructor ‘gr::plasma::lfm_source_impl::lfm_source_impl(double, double, double, double)’:
/home/raidfire/gr-plasma-1.1.0-rc1/lib/lfm_source_impl.cc:41:93: error: no matching function for call to ‘plasma::LinearFMWaveform::LinearFMWaveform(double&, double&, double&, int, double&)’
   41 |     d_waveform = ::plasma::LinearFMWaveform(bandwidth, pulse_width, samp_rate, 0, start_freq);
      |                                                                                             ^
In file included from /home/raidfire/gr-plasma-1.1.0-rc1/lib/lfm_source_impl.h:14,
                 from /home/raidfire/gr-plasma-1.1.0-rc1/lib/lfm_source_impl.cc:8:
/home/raidfire/prefix-gr310radar/include/plasma_dsp/linear_fm_waveform.h:47:3: note: candidate: ‘plasma::LinearFMWaveform::LinearFMWaveform(double, double, double, std::vector<double>)’
   47 |   LinearFMWaveform(double bandwidth, double pulse_width, double samp_rate,
      |   ^~~~~~~~~~~~~~~~
/home/raidfire/prefix-gr310radar/include/plasma_dsp/linear_fm_waveform.h:47:3: note:   candidate expects 4 arguments, 5 provided
/home/raidfire/prefix-gr310radar/include/plasma_dsp/linear_fm_waveform.h:36:3: note: candidate: ‘plasma::LinearFMWaveform::LinearFMWaveform(double, double, double, double)’
   36 |   LinearFMWaveform(double bandwidth, double pulse_width, double samp_rate,
      |   ^~~~~~~~~~~~~~~~
/home/raidfire/prefix-gr310radar/include/plasma_dsp/linear_fm_waveform.h:36:3: note:   candidate expects 4 arguments, 5 provided
/home/raidfire/prefix-gr310radar/include/plasma_dsp/linear_fm_waveform.h:26:3: note: candidate: ‘plasma::LinearFMWaveform::LinearFMWaveform()’
   26 |   LinearFMWaveform();
      |   ^~~~~~~~~~~~~~~~
/home/raidfire/prefix-gr310radar/include/plasma_dsp/linear_fm_waveform.h:26:3: note:   candidate expects 0 arguments, 5 provided
/home/raidfire/prefix-gr310radar/include/plasma_dsp/linear_fm_waveform.h:13:7: note: candidate: ‘plasma::LinearFMWaveform::LinearFMWaveform(const plasma::LinearFMWaveform&)’
   13 | class LinearFMWaveform : public PulsedWaveform {
      |       ^~~~~~~~~~~~~~~~
/home/raidfire/prefix-gr310radar/include/plasma_dsp/linear_fm_waveform.h:13:7: note:   candidate expects 1 argument, 5 provided
make[2]: *** [lib/CMakeFiles/gnuradio-plasma.dir/build.make:90: lib/CMakeFiles/gnuradio-plasma.dir/lfm_source_impl.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:249: lib/CMakeFiles/gnuradio-plasma.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by ShaneFlandermeyer** [comment]
Can you try uninstalling plasma-dsp and reinstalling through its develop branch? It looks like I might've not merged that change to the main branch. Let me know if that solves the problem!

**Comment by ShaneFlandermeyer** [comment]
Did you also uninstall/reinstall gr-plasma afterwards? If so, can you copy/paste the commit hash you're working on for both repositories?

**Comment by Raidfire-SDR** [comment]
No need because it wont make, it didnt get as far as installing


https://github.com/ShaneFlandermeyer/plasma-dsp/commit/f4f84dc460d28768061c960932c0d6a552294c85
https://github.com/ShaneFlandermeyer/gr-plasma/commit/22185f2d82c2dd89e0849994dbd001b242bc9516

**Comment by ShaneFlandermeyer** [comment]
Try this commit for plasma-dsp: ShaneFlandermeyer/plasma-dsp@d0c3503

**Comment by Raidfire-SDR** [comment]
same again, it;s getting late for me, i have an image of the vm from before i started today, i will redeploy it in the morning and start fresh with the dev branches.
While i have your attention, whats inside the usrp block a simple tx/rx with loopback? I ask because the pluto is my weapon of choice and i have several radar applications in devlopment with the device, i was planning on (with your consent) ripping open the usrp block and converting it to pluto instructions. But moving in the right direction now the main failure of radar in GR was the graphics outputs, this module could sit very nicly alongside some of my in dev systems.

**Comment by ShaneFlandermeyer** [comment]
Let me know if it's still not working on a fresh VM install. I'm running a similar setup (except I didn't install GNU radio with pybombs) and it's working properly. I'll work on getting develop merged into main in plasma-dsp when I get some free time this week.

And yes, the USRP block is just a simple UHD loopback script with a little extra logic for setting radio parameters, converting pulses to PDUs, etc. Feel free to modify it however you want!

**Comment by Raidfire-SDR** [comment]
Bingo! After some sleep and strong coffee I figured it out, nesting.....

I would suggest to anyone using pybombs follow the main install instructions first then f you fail, try these as a secondary method.

it seems with pybombs all the default paths get screwed up so here is the solution, using the DEVELOP branches dsp version 1.0.0 and gr-plasma-1.0.0 (1.10-rc1 fails).

1. If possible avoid building Arrayfire from source use one of the 2gb binary install shell files.

2. Do not install Arrayfire to your home directory, it needs to be insalled directly into the pybombs gnuradio prefix.
download into your pybombs prefix ArrayFire-v3.8.3_Linux_x86_64_CUDA-12.0.sh, chmod 775 to make executable then run
choose yes for licence, CHOOSE NO for arrayfire directory creation.
3. Build plasma_dsp with the following command - replacing the pybombs prefix with your own:   
cmake -DCMAKE_INSTALL_PREFIX=/home/username/pybombs_prefix/
This will allow the dsp install to recursivly find Arrayfire with it now being in the prefix directory.
again from the home directory extract the gr-plasma git create the build folder then from within it run the same cmake command again as we did with the dsp install
cmake -DCMAKE_INSTALL_PREFIX=/home/username/pybombs_prefix/
This will allow the gr block build to find both dsp plasma and gnuradio runtimes and complete successully.

Only Dev branch gr-plasma-1.0.0 seems to work, for the others some build ok but get lost on the plasma pybindings when you try to run a flow graph.

**Comment by ShaneFlandermeyer** [comment]
Great! I just updated the main branch of plasma-dsp, so everything should be up-to-date again. Closing this issue

**Comment by Raidfire-SDR** [comment]
thanks, all is looking good, hope you can save the method above and work it into the pyboms installation instructions

linear fm - message debug:

![image](https://user-images.githubusercontent.com/125891383/220364092-16bdbf53-f726-480c-b553-6081fbbe8333.png)
