### ISSUE TITLE
Issues with plasma_calibrate_delay

### ISSUE THREAD

**Issue by Stroke44** [ShaneFlandermeyer/gr-plasma#3]
I installed gr-plasma with the instructions.  To compile, I had to add the following line to "./lib/usrp_radar_impl.cc":
     #include <thread>
To link, I had to replace the following line in "./apps/CMakeLists.txt":
     target_link_libraries(plasma_calibrate_delay gnuradio-plasma)
to:
     target_link_libraries(plasma_calibrate_delay gnuradio-plasma Boost::program_options)

Everything seems to work, but the executable "plasma_calibrate_delay" located in "./gr-plasma-master/build/apps" does not seem to be installed as an executable accessible at the system level (i.e., from other directories like its in the system path).  I'm not sure if that's the intent.

Also, I'm using a USRP N210.  Is your code strictly for USB 3.0 USRPs?  I noticed you used a USRP B210.  I tried running:
     plasma_calibrate_delay --args="addr=192.168.10.2" --rates 10e6 20e6 --filename $HOME/delay.json
but that did not work either.

Any suggestions would be appreciated.  Thanks.

**Comment by ShaneFlandermeyer** [comment]
What kind of errors are you getting due to the lack of include statement? I can try to replicate the problem on my machine (Ubuntu 22.04).

The delay calibration should be installed system-wide, but it seems I accidentally removed that statement in the last release. Adding this after the target_link_libraries call in apps/ should install the executable properly.
# Install system-wide
install(TARGETS plasma_calibrate_delay DESTINATION bin)

The delay calibration script is designed for any UHD-compatible SDR. We've tested it on a B210, N210, and X310. What kind of errors are you getting there?

**Comment by Stroke44** [comment]
The need for "#include \<thread\>" in "./lib/usrp_radar_impl.h" was because of the following compilation error:

john@VALI:~/Dev/gr-plasma-master/build$ make
[  1%] Automatic MOC for target gnuradio-plasma
[  1%] Built target gnuradio-plasma_autogen
[  3%] Building CXX object lib/CMakeFiles/gnuradio-plasma.dir/gnuradio-plasma_autogen/mocs_compilation.cpp.o
[  5%] Building CXX object lib/CMakeFiles/gnuradio-plasma.dir/lfm_source_impl.cc.o
[  7%] Building CXX object lib/CMakeFiles/gnuradio-plasma.dir/waveform_controller_impl.cc.o
[  9%] Building CXX object lib/CMakeFiles/gnuradio-plasma.dir/usrp_radar_impl.cc.o
/home/john/Dev/gr-plasma-master/lib/usrp_radar_impl.cc: In member function ‘virtual void gr::plasma::usrp_radar_impl::set_rx_freq(double)’:
/home/john/Dev/gr-plasma-master/lib/usrp_radar_impl.cc:404:14: error: ‘std::this_thread’ has not been declared
  404 |         std::this_thread::sleep_for(std::chrono::milliseconds(100));
      |              ^~~~~~~~~~~
make[2]: *** [lib/CMakeFiles/gnuradio-plasma.dir/build.make:118: lib/CMakeFiles/gnuradio-plasma.dir/usrp_radar_impl.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:249: lib/CMakeFiles/gnuradio-plasma.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

This was under Ubuntu 20.04.6 LTS within WSL 2 on Windows 11.  That include statement and the "Boost::program_options" were needed to successfully compile and link.  That was not the case on a machine with a "bare metal" installation of Linux Mint 21.1 (Ubuntu 22.04).  Both machines had the issue with installing "plasma_calibrate_delay" system-wide, but your above addition of the "install" line worked.

Thanks.

**Comment by Stroke44** [comment]
I'm still having difficulty getting "plasma_calibrate_delay" to talk to my USRP N210.  On my "bare metal" Linux laptop, I verified the N210 is connected via ping, identified by UHD, and runs GNU Radio 3.10 flowgraphs with USRP sources and sinks.  What is the proper syntax for "plasma_calibrate_delay"?  This is what I've tried:
```
john@ULLR:~$ uhd_find_devices --args "addr=192.168.10.2"
[INFO] [UHD] linux; GNU C++ version 11.2.0; Boost_107400; UHD_4.1.0.5-3
--------------------------------------------------
-- UHD Device 0
--------------------------------------------------
Device Address:
    serial: E9R1CR3UP
    addr: 192.168.10.2
    name: 
    type: usrp2


john@ULLR:~$ plasma_calibrate_delay --args "addr=192.168.10.2" --rates 10e6 20e6 --filename $HOME/delay.json
ArrayFire v3.8.3 (CPU, 64-bit Linux, build 987d5675a)
[INFO] [UHD] linux; GNU C++ version 11.2.0; Boost_107400; UHD_4.1.0.5-3
[0] Intel: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHzError: LookupError: KeyError: No devices found for ----->
Empty Device Address

john@ULLR:~$ plasma_calibrate_delay --rates 10e6 20e6 --filename $HOME/delay.json
ArrayFire v3.8.3 (CPU, 64-bit Linux, build 987d5675a)
[INFO] [UHD] linux; GNU C++ version 11.2.0; Boost_107400; UHD_4.1.0.5-3
[0] Intel: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHzError: LookupError: KeyError: No devices found for ----->
Empty Device Address

john@ULLR:~$ plasma_calibrate_delay --args="addr=192.168.10.2" --rates 10e6 20e6 --filename $HOME/delay.json
ArrayFire v3.8.3 (CPU, 64-bit Linux, build 987d5675a)
[INFO] [UHD] linux; GNU C++ version 11.2.0; Boost_107400; UHD_4.1.0.5-3
[0] Intel: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHzError: LookupError: KeyError: No devices found for ----->
Empty Device Address

``` 
Thanks.

**Comment by ShaneFlandermeyer** [comment]
That's odd. The syntax is correct, but it looks like multi_usrp::make is failing on the UHD side. I ran the script successfully on my B210 earlier today, but I'll try again with the X310 in the morning to make sure there's no weirdness with ethernet-based SDRs.

**Comment by ShaneFlandermeyer** [comment]
Just tested it, and it's working on my end. Have you tried reinstalling UHD? Here's my output:

$ uhd_find_devices --args="addr=192.168.30.2"
[INFO] [UHD] linux; GNU C++ version 11.3.0; Boost_107400; DPDK_21.11; UHD_4.4.0.HEAD-0-g5fac246b
--------------------------------------------------
-- UHD Device 0
--------------------------------------------------
Device Address:
    serial: 31EC214
    addr: 192.168.30.2
    fpga: XG
    name: 
    product: X310
    type: x300

$ plasma_calibrate_delay --args="addr=192.168.30.2" --filename=$HOME/delay.json --tx_gain=10 --rx_gain=10 --rates 10e6 20e6
ArrayFire v3.8.2 (CUDA, 64-bit Linux, build 5752f2dc)
Platform: CUDA Runtime 11.6, Driver: 530.30.02
[0] Quadro RTX 5000, 16118 MB, CUDA Compute 7.5
-1- Quadro RTX 5000, 16110 MB, CUDA Compute 7.5
[INFO] [UHD] linux; GNU C++ version 11.3.0; Boost_107400; DPDK_21.11; UHD_4.4.0.HEAD-0-g5fac246b
[INFO] [X300] X300 initialization sequence...
[INFO] [X300] Maximum frame size: 8000 bytes.
[INFO] [X300] Radio 1x clock: 200 MHz
[WARNING] [RFNOC::GRAPH::DETAIL] Cannot forward action tx_event from 0/Radio#0:INPUT_EDGE:0, no neighbour found!
[INFO] [CALIBRATE_DELAY] At MCR = 200 MHz, sample rate = 10 MHz, delay is 39 samples
[INFO] [X300] X300 initialization sequence...
[INFO] [X300] Maximum frame size: 8000 bytes.
[INFO] [X300] Radio 1x clock: 200 MHz
[WARNING] [RFNOC::GRAPH::DETAIL] Cannot forward action tx_event from 0/Radio#0:INPUT_EDGE:0, no neighbour found!
[INFO] [CALIBRATE_DELAY] At MCR = 200 MHz, sample rate = 20 MHz, delay is 35 samples

**Comment by Stroke44** [comment]
This is what I get on my Windows 11 / WSL 2 machine:
```
john@VALI:~/Documents/gnuradio$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
john@VALI:~/Documents/gnuradio$ uhd_find_devices --args="addr=192.168.10.2"
[INFO] [UHD] linux; GNU C++ version 9.2.1 20200304; Boost_107100; UHD_3.15.0.0-2build5
--------------------------------------------------
-- UHD Device 0
--------------------------------------------------
Device Address:
    serial: E9R1CR3UP
    addr: 192.168.10.2
    name:
    type: usrp2


john@VALI:~/Documents/gnuradio$ plasma_calibrate_delay --args="addr=192.168.10.2" --filename=$HOME/delay.json --tx_gain=10 --rx_gain=10 --rates 10e6 20e6
ArrayFire v3.8.3 (CUDA, 64-bit Linux, build 987d5675a)
Platform: CUDA Runtime 12.0, Driver: N/A
[0] NVIDIA GeForce RTX 3070, 8192 MB, CUDA Compute 8.6
[INFO] [UHD] linux; GNU C++ version 9.2.1 20200304; Boost_107100; UHD_3.15.0.0-2build5
Error: LookupError: KeyError: No devices found for ----->
Empty Device Address
``` 
Is there an issue with version numbers?

- You have:  GNU C++ version 11.3.0; Boost_107400; DPDK_21.11; UHD_4.4.0.HEAD-0-g5fac246b

- I have: GNU C++ version 9.2.1 20200304; Boost_107100; UHD_3.15.0.0-2build5

Thanks.

**Comment by Stroke44** [comment]
This is what I get on my "bare metal" Linux Mint 21.1 (Ubuntu 22.04) laptop:
```
ohn@ULLR:~/Documents/GNU_Radio/Working/GR310$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21.1
Release:	21.1
Codename:	vera
john@ULLR:~/Documents/GNU_Radio/Working/GR310$ uhd_find_devices --args="addr=192.168.10.2"
[INFO] [UHD] linux; GNU C++ version 11.2.0; Boost_107400; UHD_4.1.0.5-3
--------------------------------------------------
-- UHD Device 0
--------------------------------------------------
Device Address:
    serial: E9R1CR3UP
    addr: 192.168.10.2
    name: 
    type: usrp2


john@ULLR:~/Documents/GNU_Radio/Working/GR310$ plasma_calibrate_delay --args="addr=192.168.10.2" --filename=$HOME/delay.json --tx_gain=10 --rx_gain=10 --rates 10e6 20e6
ArrayFire v3.8.3 (CPU, 64-bit Linux, build 987d5675a)
[INFO] [UHD] linux; GNU C++ version 11.2.0; Boost_107400; UHD_4.1.0.5-3
[0] Intel: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHzError: LookupError: KeyError: No devices found for ----->
Empty Device Address
``` 
Again, there are version differences:

- You have: GNU C++ version 11.3.0; Boost_107400; DPDK_21.11; UHD_4.4.0.HEAD-0-g5fac246b

- I have: GNU C++ version 11.2.0; Boost_107400; UHD_4.1.0.5-3

Both systems ran the attached GNU Radio flowgraph fine, which consisted of a cabled (with attenuators) wrap-around on the same USRP N210.
![test_gr310_usrp_grc](https://user-images.githubusercontent.com/23583798/235040620-349c062a-0a94-4ba1-9b8f-259a57990391.png)

Thanks.

**Comment by Stroke44** [comment]
BTW, I did re-install UHD.

**Comment by 151ashlyn** [comment]
hi,i met problems as below:
ake[2]: *** [apps/CMakeFiles/plasma_calibrate_delay.dir/build.make:131：apps/plasma_calibrate_delay] erroe1
make[1]: *** [CMakeFiles/Makefile2:408：apps/CMakeFiles/plasma_calibrate_delay.dir/all] 错误 2
make: *** [Makefile:146：all] erroe 2
and i do not know how to fix it,please could tell me how to fix it?

**Comment by 151ashlyn** [comment]
should i uninstall plasma-dsp and gr plasma ,and re-install them again?is there any other solutions?

**Comment by ShaneFlandermeyer** [comment]
Months-late update: I have removed the C++ version of this script in the latest release and am working on a Python version. Hoping this solves everyone's problems
