### ISSUE TITLE
Problems with log4cpp

### ISSUE THREAD

**Issue by santi0069** [ShaneFlandermeyer/gr-plasma#4]
Hello I'm trying to install the package in my ubuntu GNU-Radio but when I do the `make` inside the build it always appear this message:

`[ 46%] Automatic MOC for target plasma_qa_cfar2D.cc
[ 46%] Built target plasma_qa_cfar2D.cc_autogen
[ 48%] Linking CXX executable plasma_qa_cfar2D.cc
/usr/bin/ld: CMakeFiles/plasma_qa_cfar2D.cc.dir/qa_cfar2D.cc.o: 
in function _GLOBAL__sub_I_qa_cfar2D.cc':
qa_cfar2D.cc:(.text.startup+0x44): undefined reference to log4cpp::Appender::AppenderMapStorageInitializer::AppenderMapStorageInitializer()
/usr/bin/ld: qa_cfar2D.cc:(.text.startup+0x4b): undefined reference to log4cpp::Appender::AppenderMapStorageInitializer::~AppenderMapStorageInitializer()'
collect2: error: ld returned 1 exit status
make[2]: *** [lib/CMakeFiles/plasma_qa_cfar2D.cc.dir/build.make:117: lib/plasma_qa_cfar2D.cc] Error 1
make[1]: *** [CMakeFiles/Makefile2:293: lib/CMakeFiles/plasma_qa_cfar2D.cc.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
`
 
If someone find the same problem or have the solution please answer that, thank you

**Comment by ShaneFlandermeyer** [comment]
What version of log4cpp are you using? The install runs successfully for me on Ubuntu 22.04. Here's the relevant info when I run apt show

$ apt show liblog4cpp5-dev

Package: liblog4cpp5-dev
Version: 1.1.3-3
Priority: optional
Section: universe/libdevel
Source: log4cpp
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: A. Maitland Bottoms <bottoms@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 947 kB
Depends: liblog4cpp5v5 (= 1.1.3-3)
Conflicts: liblog4cpp-dev, liblog4cpp1-dev, liblog4cpp3-dev, liblog4cpp4-dev
Replaces: liblog4cpp-dev, liblog4cpp1-dev, liblog4cpp3-dev, liblog4cpp4-dev
Homepage: http://log4cpp.sourceforge.net
Download-Size: 127 kB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages

**Comment by santi0069** [comment]
I'm using almost the same

Package: liblog4cpp5-dev
Version: 1.1.3-1ubuntu1
Priority: optional
Section: universe/libdevel
Source: log4cpp
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: A. Maitland Bottoms <bottoms@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 947 kB
Depends: liblog4cpp5v5 (= 1.1.3-1ubuntu1)
Conflicts: liblog4cpp-dev, liblog4cpp1-dev, liblog4cpp3-dev, liblog4cpp4-dev
Replaces: liblog4cpp-dev, liblog4cpp1-dev, liblog4cpp3-dev, liblog4cpp4-dev
Homepage: http://log4cpp.sourceforge.net
Download-Size: 128 kB
APT-Manual-Installed: yes
APT-Sources: http://de.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
Description: C++ library for flexible logging (development)
 Log for C++ is a library of C++ classes for flexible logging to files,
 syslog and other destinations. It is modeled after the Log for
 Java library (http://jakarta.apache.org/log4j/), staying as close to
 their API as is reasonable.

**Comment by santi0069** [comment]
![Error](https://github.com/ShaneFlandermeyer/gr-plasma/assets/58419963/f13446dd-0549-4853-8889-e88b08bf5a19)

**Comment by ShaneFlandermeyer** [comment]
How did you install GNU Radio? It's strange that qa_phase_code builds and links but the qa_cfar2d doesn't. 

Either way, those files don't actually do anything, so you can comment out lines 85-86 in lib/CMakeLists.txt and try building again.

**Comment by santi0069** [comment]
I change this 
`list(APPEND test_plasma_sources
qa_cfar2D.cc
qa_phase_code.cc
)`

to this

`#list(APPEND test_plasma_sources
#qa_cfar2D.cc
#qa_phase_code.cc
![Error2](https://github.com/ShaneFlandermeyer/gr-plasma/assets/58419963/bd29e431-227b-4ae0-9f1c-5f1beb38976b)

#)`
On the file gr-plasma/lib/CMakeList.txt

And the result is:

**Comment by h57jafari** [comment]
it seems that I have the same problem at 52%, could you solve it?

**Comment by ShaneFlandermeyer** [comment]
These build issues should be fixed in the latest release!
