### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by 151ashlyn** [ShaneFlandermeyer/gr-plasma#6]
ake[2]: *** [apps/CMakeFiles/plasma_calibrate_delay.dir/build.make:131：apps/plasma_calibrate_delay] error 1
make[1]: *** [CMakeFiles/Makefile2:408：apps/CMakeFiles/plasma_calibrate_delay.dir/all] error2
make: *** [Makefile:146：all] error2
could you please tell me what to do next?in the eariler issue your solution is reinstall the plasma-dsp and gr-plasma,is there any other ways?

**Comment by ShaneFlandermeyer** [comment]
The most recent release eliminates this build issue. For more discussion, see #5
