### ISSUE TITLE
Error casting to pmt::intern

### ISSUE THREAD

**Issue by ss32** [ShaneFlandermeyer/gr-plasma#7]
My build failed on [pdu_file_source_impl.cc:40](https://github.com/ShaneFlandermeyer/gr-plasma/blob/2209fd88dd72bc344cfd75a629ee1589bdaf07d1/lib/pdu_file_source_impl.cc#L91) 

```
 error: could not convert ‘value’ from ‘nlohmann::json’ {aka ‘nlohmann::basic_json<>’} to ‘std::string_view’ {aka ‘std::basic_string_view<char>’}
 ```

I corrected it by casting to `std::string` but there might be a more intelligent way to fix it

```cpp
            if (value.is_string())
                pmt_value = pmt::intern(std::string{value});
```

`json.hpp` `v3.7.3`

**Comment by ShaneFlandermeyer** [comment]
Completely forgot to come back to this issue, but this problem is fixed in both the develop and main branch.
