### ISSUE TITLE
Fixed range and velocity in range doppler sink

### ISSUE THREAD

**Issue by fllay** [ShaneFlandermeyer/gr-plasma#8]
Is it possible to  fix range and velocity in range doppler sink? It seems that the range and velocity x-axis and y-axis is set to auto-range. I need to specify the maximum value for both range and velocity. Thank you

**Comment by ShaneFlandermeyer** [comment]
Unfortunately, the block in the current main/develop branches only supports autoscaling and manual zoom. If you look in commit a953bd9 in the nwf-demo branch, I did hack together a way to set the range scale via PMT messages. Adapting that commit to also handle the velocity scaling would be pretty straightforward. 

I agree that this feature would be useful. I will add it to my list of features to implement in the next release!

**Comment by fllay** [comment]
thank you. I will try that commit.
